import type { AppLocale } from "@/lib/i18n/locales";
import { defineUiCopy } from "@/lib/i18n/copy";

export const EDITOR_COPY = defineUiCopy({
  en: {
    todoComplete: "Mark to-do complete",
    imageUploading: "Uploading image",
    urlRequired: "Enter a URL.",
    httpOnly: "Only http or https URLs can be used.",
    internalDocumentRequired: "Select an internal document to link.",
    linkApplyFailed: "Could not apply the link.",
    formattingToolbar: "Document formatting",
    horizontalToolbarHint: "Drag horizontally when the tools are wider than the window.",
    undo: "Undo",
    redo: "Redo",
    blockType: "Block type",
    body: "Body",
    heading1: "Heading 1",
    heading2: "Heading 2",
    heading3: "Heading 3",
    heading4: "Heading 4",
    heading5: "Heading 5",
    heading6: "Heading 6",
    quote: "Quote",
    callout: "Callout",
    fontSize: "Font size",
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    strikethrough: "Strikethrough",
    inlineCode: "Inline code",
    linkAddOrEdit: "Add or edit link",
    linkEditor: "Edit link",
    linkKind: "Link type",
    externalLink: "External link",
    internalDocument: "Internal document",
    linkUrl: "Link URL",
    displayTitle: "Display title",
    automaticTitle: "Leave blank to fetch the page title automatically",
    internalDocumentSearch: "Search internal documents",
    documentSearchPlaceholder: "Search by document name or path",
    noMatchingDocuments: "No matching documents.",
    checking: "Checking…",
    apply: "Apply",
    close: "Close",
    unlink: "Remove link",
    textColor: "Text color",
    backgroundColor: "Background color",
    alignLeft: "Align left",
    alignCenter: "Align center",
    alignRight: "Align right",
    alignJustify: "Justify",
    bulletList: "Bulleted list",
    numberedList: "Numbered list",
    todoList: "To-do list",
    outdent: "Outdent",
    indent: "Indent",
    insertCodeBlock: "Insert code block",
    insertTable: "Insert 3 × 3 table",
    addRowBelow: "Add row below",
    deleteSelectedRow: "Delete selected row",
    addColumnRight: "Add column to the right",
    deleteSelectedColumn: "Delete selected column",
    mergeSelectedCells: "Merge selected cells",
    splitCell: "Split cell",
    deleteTable: "Delete entire table",
    keyboardShortcuts: "Keyboard shortcuts",
    shortcutDescription: "Use familiar Notion key combinations for features available in Nyxdoc.",
    shortcutClose: "Close keyboard shortcut help",
    shortcutUnsupported: "Features not yet available in Nyxdoc, such as comments and toggles, are not shown as supported.",
    uploadsPending: "Uploading {count} images",
    dismiss: "Dismiss",
    documentBody: "Document body",
    bodyPlaceholder: "Type your content",
    collaborationAuthFailed: "Could not authenticate the collaboration connection.",
    collaborativeDraftFailed: "Could not open the shared draft.",
    imageLimit: "You can paste up to 5 images at a time.",
    clipboardImage: "Clipboard image",
    imageUploadFailed: "Could not upload the image.",
    workspace: "Workspace",
    beforeSaveConnection: "Not connected to saving",
    closeValidationPanel: "Close validation panel",
    openValidationPanel: "Open validation panel",
    nextEditor: "Next-generation document editor",
    selectingCommand: "Selecting command",
    astValid: "AST v2 valid",
    astNeedsValidation: "AST v2 needs validation",
    uploadStatusDescription: "When the upload finishes, the temporary preview is replaced with an authenticated media link.",
    slashStatusDescription: "Choose a slash command to convert the temporary input into a savable block.",
    validStatusDescription: "The current content matches the new storage contract.",
    validationRuleCount: "Review {count} validation rules.",
    labKicker: "FIRST VERTICAL SLICE",
    labHeading: "Validate the editing fundamentals first",
    labDescription: "This screen does not save to production documents. It is an isolated lab for validating core editing behavior.",
    showCurrentJson: "View current Nyxdoc JSON",
    validationErrors: "Validation errors",
    sampleTitle: "Next-generation Nyxdoc editor",
    sampleIntroPrefix: "In one document, ",
    sampleHuman: "people",
    sampleIntroJoin: " and ",
    sampleAgent: "agents",
    sampleIntroSuffix: " share the same structure and history.",
    sampleMultiline: "Press Shift+Enter in this paragraph to create multiple lines in the same block.\nThis existing line is also the second line of the same block.",
    sampleFontPrefix: "This sentence uses the default size, and ",
    sampleFontLarge: "this part is 24px.",
    sampleCentered: "This paragraph is center-aligned.",
    sampleListFirst: "Type after a hyphen and press Enter to continue the list.",
    sampleListSecond: "Use Tab and Shift+Tab to change the list depth.",
    sampleTableCheck: "Check",
    sampleTableAction: "Action",
    sampleTableExpected: "Expected result",
    sampleTableMultiCell: "Select multiple cells",
    sampleTableDrag: "Drag across cells",
    sampleTableHighlight: "Selection is highlighted",
    sampleTableCopyPaste: "Copy and paste",
    sampleTableMatrix: "Cell matrix is preserved",
    sampleGuideTitle: "Operations guide",
    sampleGuidePath: "Guides / Operations guide",
    samplePolicyTitle: "Sharing policy",
    samplePolicyPath: "Guides / Policies / Sharing policy",
  },
  ko: {
    todoComplete: "할 일 완료",
    imageUploading: "이미지 업로드 중",
    urlRequired: "주소를 입력하세요.",
    httpOnly: "http 또는 https 주소만 사용할 수 있습니다.",
    internalDocumentRequired: "연결할 내부 문서를 선택하세요.",
    linkApplyFailed: "링크를 적용하지 못했습니다.",
    formattingToolbar: "문서 서식",
    horizontalToolbarHint: "도구가 길면 좌우로 드래그하여 이동할 수 있습니다.",
    undo: "실행 취소",
    redo: "다시 실행",
    blockType: "문단 유형",
    body: "본문",
    heading1: "제목 1",
    heading2: "제목 2",
    heading3: "제목 3",
    heading4: "제목 4",
    heading5: "제목 5",
    heading6: "제목 6",
    quote: "인용",
    callout: "콜아웃",
    fontSize: "글자 크기",
    bold: "굵게",
    italic: "기울임",
    underline: "밑줄",
    strikethrough: "취소선",
    inlineCode: "인라인 코드",
    linkAddOrEdit: "링크 추가 또는 편집",
    linkEditor: "링크 편집",
    linkKind: "링크 종류",
    externalLink: "외부 링크",
    internalDocument: "내부 문서",
    linkUrl: "링크 주소",
    displayTitle: "표시할 제목",
    automaticTitle: "비우면 페이지 제목을 자동으로 가져옵니다",
    internalDocumentSearch: "내부 문서 검색",
    documentSearchPlaceholder: "문서 이름이나 경로 검색",
    noMatchingDocuments: "일치하는 문서가 없습니다.",
    checking: "확인 중…",
    apply: "적용",
    close: "닫기",
    unlink: "링크 해제",
    textColor: "글자색",
    backgroundColor: "배경색",
    alignLeft: "왼쪽 정렬",
    alignCenter: "가운데 정렬",
    alignRight: "오른쪽 정렬",
    alignJustify: "양쪽 정렬",
    bulletList: "글머리 목록",
    numberedList: "번호 목록",
    todoList: "할 일 목록",
    outdent: "내어쓰기",
    indent: "들여쓰기",
    insertCodeBlock: "코드 블록 삽입",
    insertTable: "3 × 3 표 삽입",
    addRowBelow: "아래에 행 추가",
    deleteSelectedRow: "선택한 행 삭제",
    addColumnRight: "오른쪽에 열 추가",
    deleteSelectedColumn: "선택한 열 삭제",
    mergeSelectedCells: "선택 셀 병합",
    splitCell: "셀 나누기",
    deleteTable: "표 전체 삭제",
    keyboardShortcuts: "키보드 단축키",
    shortcutDescription: "Nyxdoc에 있는 기능은 익숙한 Notion 키 조합으로 사용할 수 있습니다.",
    shortcutClose: "단축키 도움말 닫기",
    shortcutUnsupported: "댓글·토글처럼 Nyxdoc에 아직 없는 기능은 지원하는 것처럼 표시하지 않습니다.",
    uploadsPending: "이미지 {count}개 업로드 중",
    dismiss: "닫기",
    documentBody: "문서 본문",
    bodyPlaceholder: "내용을 입력하세요",
    collaborationAuthFailed: "협업 연결 인증에 실패했습니다.",
    collaborativeDraftFailed: "공유 초안을 열지 못했습니다.",
    imageLimit: "한 번에 이미지는 5개까지 붙여넣을 수 있습니다.",
    clipboardImage: "클립보드 이미지",
    imageUploadFailed: "이미지 업로드에 실패했습니다.",
    workspace: "워크스페이스",
    beforeSaveConnection: "저장 연결 전",
    closeValidationPanel: "검증 패널 닫기",
    openValidationPanel: "검증 패널 열기",
    nextEditor: "차세대 문서 편집기",
    selectingCommand: "명령 선택 중",
    astValid: "AST v2 유효",
    astNeedsValidation: "AST v2 검증 필요",
    uploadStatusDescription: "업로드가 끝나면 임시 미리보기가 인증된 미디어 링크로 바뀝니다.",
    slashStatusDescription: "슬래시 입력은 명령을 고르면 저장 가능한 블록으로 바뀝니다.",
    validStatusDescription: "현재 내용은 새 저장 계약과 일치합니다.",
    validationRuleCount: "{count}개 규칙을 확인하세요.",
    labKicker: "FIRST VERTICAL SLICE",
    labHeading: "편집 기본기부터 검증",
    labDescription: "이 화면은 운영 문서에 저장하지 않습니다. 편집 기본기가 맞는지 먼저 확인하는 격리된 실험실입니다.",
    showCurrentJson: "현재 Nyxdoc JSON 보기",
    validationErrors: "검증 오류",
    sampleTitle: "차세대 Nyxdoc 편집기",
    sampleIntroPrefix: "한 문서 안에서 ",
    sampleHuman: "사람",
    sampleIntroJoin: "과 ",
    sampleAgent: "에이전트",
    sampleIntroSuffix: "가 같은 구조와 기록을 봅니다.",
    sampleMultiline: "이 문단에서 Shift+Enter를 눌러 같은 블록 안에 여러 줄을 만들어 보세요.\n이미 들어 있는 이 줄도 같은 블록의 두 번째 줄입니다.",
    sampleFontPrefix: "이 문장은 기본 크기이고, ",
    sampleFontLarge: "이 부분은 24px입니다.",
    sampleCentered: "이 문단은 가운데 정렬되어 있습니다.",
    sampleListFirst: "하이픈 뒤에 글을 쓰고 Enter를 눌러 목록을 이어갑니다.",
    sampleListSecond: "Tab과 Shift+Tab으로 목록 깊이를 바꿉니다.",
    sampleTableCheck: "검증 항목",
    sampleTableAction: "조작",
    sampleTableExpected: "기대 결과",
    sampleTableMultiCell: "여러 셀 선택",
    sampleTableDrag: "셀을 드래그",
    sampleTableHighlight: "선택 영역 강조",
    sampleTableCopyPaste: "복사와 붙여넣기",
    sampleTableMatrix: "셀 행렬 유지",
    sampleGuideTitle: "운영 안내",
    sampleGuidePath: "가이드 / 운영 안내",
    samplePolicyTitle: "공유 정책",
    samplePolicyPath: "가이드 / 정책 / 공유 정책",
  },
  ja: {
    todoComplete: "To-doを完了にする",
    imageUploading: "画像をアップロード中",
    urlRequired: "URLを入力してください。",
    httpOnly: "httpまたはhttpsのURLのみ使用できます。",
    internalDocumentRequired: "リンクする内部文書を選択してください。",
    linkApplyFailed: "リンクを適用できませんでした。",
    formattingToolbar: "文書の書式",
    horizontalToolbarHint: "ツールが画面より長い場合は、左右にドラッグして移動できます。",
    undo: "元に戻す",
    redo: "やり直す",
    blockType: "ブロックの種類",
    body: "本文",
    heading1: "見出し 1",
    heading2: "見出し 2",
    heading3: "見出し 3",
    heading4: "見出し 4",
    heading5: "見出し 5",
    heading6: "見出し 6",
    quote: "引用",
    callout: "コールアウト",
    fontSize: "文字サイズ",
    bold: "太字",
    italic: "斜体",
    underline: "下線",
    strikethrough: "取り消し線",
    inlineCode: "インラインコード",
    linkAddOrEdit: "リンクを追加または編集",
    linkEditor: "リンクを編集",
    linkKind: "リンクの種類",
    externalLink: "外部リンク",
    internalDocument: "内部文書",
    linkUrl: "リンクURL",
    displayTitle: "表示タイトル",
    automaticTitle: "空欄にするとページタイトルを自動取得します",
    internalDocumentSearch: "内部文書を検索",
    documentSearchPlaceholder: "文書名またはパスで検索",
    noMatchingDocuments: "一致する文書がありません。",
    checking: "確認中…",
    apply: "適用",
    close: "閉じる",
    unlink: "リンクを解除",
    textColor: "文字色",
    backgroundColor: "背景色",
    alignLeft: "左揃え",
    alignCenter: "中央揃え",
    alignRight: "右揃え",
    alignJustify: "両端揃え",
    bulletList: "箇条書き",
    numberedList: "番号付きリスト",
    todoList: "To-doリスト",
    outdent: "インデントを減らす",
    indent: "インデントを増やす",
    insertCodeBlock: "コードブロックを挿入",
    insertTable: "3 × 3の表を挿入",
    addRowBelow: "下に行を追加",
    deleteSelectedRow: "選択した行を削除",
    addColumnRight: "右に列を追加",
    deleteSelectedColumn: "選択した列を削除",
    mergeSelectedCells: "選択したセルを結合",
    splitCell: "セルを分割",
    deleteTable: "表全体を削除",
    keyboardShortcuts: "キーボードショートカット",
    shortcutDescription: "Nyxdocで利用できる機能は、使い慣れたNotionのキー操作で実行できます。",
    shortcutClose: "キーボードショートカットのヘルプを閉じる",
    shortcutUnsupported: "コメントやトグルなど、Nyxdocでまだ利用できない機能は対応済みとして表示しません。",
    uploadsPending: "{count}件の画像をアップロード中",
    dismiss: "閉じる",
    documentBody: "文書本文",
    bodyPlaceholder: "内容を入力",
    collaborationAuthFailed: "共同編集接続の認証に失敗しました。",
    collaborativeDraftFailed: "共有下書きを開けませんでした。",
    imageLimit: "一度に貼り付けられる画像は5件までです。",
    clipboardImage: "クリップボード画像",
    imageUploadFailed: "画像をアップロードできませんでした。",
    workspace: "ワークスペース",
    beforeSaveConnection: "保存に未接続",
    closeValidationPanel: "検証パネルを閉じる",
    openValidationPanel: "検証パネルを開く",
    nextEditor: "次世代文書エディター",
    selectingCommand: "コマンドを選択中",
    astValid: "AST v2 有効",
    astNeedsValidation: "AST v2 の検証が必要",
    uploadStatusDescription: "アップロードが完了すると、仮のプレビューが認証済みメディアリンクに置き換わります。",
    slashStatusDescription: "スラッシュコマンドを選ぶと、一時入力が保存可能なブロックに変わります。",
    validStatusDescription: "現在の内容は新しい保存契約に一致しています。",
    validationRuleCount: "{count}件の規則を確認してください。",
    labKicker: "FIRST VERTICAL SLICE",
    labHeading: "まず編集の基本機能を検証",
    labDescription: "この画面は運用文書に保存されません。編集の基本動作を検証するための隔離されたラボです。",
    showCurrentJson: "現在のNyxdoc JSONを表示",
    validationErrors: "検証エラー",
    sampleTitle: "次世代Nyxdocエディター",
    sampleIntroPrefix: "1つの文書で、",
    sampleHuman: "人",
    sampleIntroJoin: "と",
    sampleAgent: "エージェント",
    sampleIntroSuffix: "が同じ構造と履歴を共有します。",
    sampleMultiline: "この段落でShift+Enterを押し、同じブロック内に複数行を作ってみてください。\nこの行も同じブロックの2行目です。",
    sampleFontPrefix: "この文は標準サイズで、",
    sampleFontLarge: "この部分は24pxです。",
    sampleCentered: "この段落は中央揃えです。",
    sampleListFirst: "ハイフンの後に入力してEnterを押すと、リストが続きます。",
    sampleListSecond: "TabとShift+Tabでリストの深さを変更します。",
    sampleTableCheck: "検証項目",
    sampleTableAction: "操作",
    sampleTableExpected: "期待結果",
    sampleTableMultiCell: "複数セルを選択",
    sampleTableDrag: "セルをドラッグ",
    sampleTableHighlight: "選択範囲を強調",
    sampleTableCopyPaste: "コピーと貼り付け",
    sampleTableMatrix: "セル行列を維持",
    sampleGuideTitle: "運用ガイド",
    sampleGuidePath: "ガイド / 運用ガイド",
    samplePolicyTitle: "共有ポリシー",
    samplePolicyPath: "ガイド / ポリシー / 共有ポリシー",
  },
});

type ShortcutGroup = {
  title: string;
  items: readonly (readonly [string, string])[];
};

export const EDITOR_SHORTCUT_GROUPS: Record<AppLocale, readonly ShortcutGroup[]> = {
  en: [
    {
      title: "Save and actions",
      items: [
        ["Ctrl/⌘ S", "Save document"],
        ["Ctrl/⌘ Z", "Undo"],
        ["Ctrl/⌘ Shift Z · Ctrl Y", "Redo"],
        ["Ctrl/⌘ D", "Duplicate current block"],
        ["Ctrl/⌘ Shift ↑/↓", "Move current block"],
      ],
    },
    {
      title: "Text formatting",
      items: [
        ["Ctrl/⌘ B", "Bold"],
        ["Ctrl/⌘ I", "Italic"],
        ["Ctrl/⌘ U", "Underline"],
        ["Ctrl/⌘ Shift S", "Strikethrough"],
        ["Ctrl/⌘ E", "Inline code"],
        ["Ctrl/⌘ Alt 8", "Code block"],
        ["Ctrl/⌘ K", "Add or edit link"],
      ],
    },
    {
      title: "Blocks and lists",
      items: [
        ["Ctrl+Shift / ⌘⌥ + 0…3", "Body and headings 1–3"],
        ["Ctrl+Shift / ⌘⌥ + 4…6", "To-do, bulleted, and numbered lists"],
        ["Tab / Shift Tab", "Indent or outdent list"],
        ["Ctrl/⌘ Enter", "Toggle to-do completion"],
        ["Enter / Shift Enter", "New block / line break within block"],
      ],
    },
    {
      title: "Markdown and commands",
      items: [
        ["# · ## · ### + Space", "Headings 1–3"],
        ["\" (or >) + Space", "Quote"],
        ["- · * · + · 1. · [] + Space", "Lists"],
        ["---", "Divider"],
        ["```", "Code block"],
        ["/", "Open block commands"],
      ],
    },
  ],
  ko: [
    {
      title: "저장과 실행",
      items: [
        ["Ctrl/⌘ S", "문서 저장"],
        ["Ctrl/⌘ Z", "실행 취소"],
        ["Ctrl/⌘ Shift Z · Ctrl Y", "다시 실행"],
        ["Ctrl/⌘ D", "현재 블록 복제"],
        ["Ctrl/⌘ Shift ↑/↓", "현재 블록 이동"],
      ],
    },
    {
      title: "글자 서식",
      items: [
        ["Ctrl/⌘ B", "굵게"],
        ["Ctrl/⌘ I", "기울임"],
        ["Ctrl/⌘ U", "밑줄"],
        ["Ctrl/⌘ Shift S", "취소선"],
        ["Ctrl/⌘ E", "인라인 코드"],
        ["Ctrl/⌘ Alt 8", "코드 블록"],
        ["Ctrl/⌘ K", "링크 추가 또는 편집"],
      ],
    },
    {
      title: "블록과 목록",
      items: [
        ["Ctrl+Shift / ⌘⌥ + 0…3", "본문·제목 1~3"],
        ["Ctrl+Shift / ⌘⌥ + 4…6", "할 일·글머리·번호 목록"],
        ["Tab / Shift Tab", "목록 들여쓰기·내어쓰기"],
        ["Ctrl/⌘ Enter", "할 일 완료 전환"],
        ["Enter / Shift Enter", "새 블록 / 블록 안 줄바꿈"],
      ],
    },
    {
      title: "Markdown과 명령",
      items: [
        ["# · ## · ### + Space", "제목 1~3"],
        ["\" (또는 >) + Space", "인용"],
        ["- · * · + · 1. · [] + Space", "목록"],
        ["---", "구분선"],
        ["```", "코드 블록"],
        ["/", "블록 명령 열기"],
      ],
    },
  ],
  ja: [
    {
      title: "保存と操作",
      items: [
        ["Ctrl/⌘ S", "文書を保存"],
        ["Ctrl/⌘ Z", "元に戻す"],
        ["Ctrl/⌘ Shift Z · Ctrl Y", "やり直す"],
        ["Ctrl/⌘ D", "現在のブロックを複製"],
        ["Ctrl/⌘ Shift ↑/↓", "現在のブロックを移動"],
      ],
    },
    {
      title: "文字書式",
      items: [
        ["Ctrl/⌘ B", "太字"],
        ["Ctrl/⌘ I", "斜体"],
        ["Ctrl/⌘ U", "下線"],
        ["Ctrl/⌘ Shift S", "取り消し線"],
        ["Ctrl/⌘ E", "インラインコード"],
        ["Ctrl/⌘ Alt 8", "コードブロック"],
        ["Ctrl/⌘ K", "リンクを追加または編集"],
      ],
    },
    {
      title: "ブロックとリスト",
      items: [
        ["Ctrl+Shift / ⌘⌥ + 0…3", "本文・見出し1～3"],
        ["Ctrl+Shift / ⌘⌥ + 4…6", "To-do・箇条書き・番号付きリスト"],
        ["Tab / Shift Tab", "リストのインデントを増減"],
        ["Ctrl/⌘ Enter", "To-doの完了を切り替え"],
        ["Enter / Shift Enter", "新しいブロック / ブロック内改行"],
      ],
    },
    {
      title: "Markdownとコマンド",
      items: [
        ["# · ## · ### + Space", "見出し1～3"],
        ["\"（または >）+ Space", "引用"],
        ["- · * · + · 1. · [] + Space", "リスト"],
        ["---", "区切り線"],
        ["```", "コードブロック"],
        ["/", "ブロックコマンドを開く"],
      ],
    },
  ],
};

export const EDITOR_LAB_CHECKS: Record<
  AppLocale,
  readonly (readonly [string, string])[]
> = {
  en: [
    ["Multiple lines and blocks", "Use Shift+Enter for a line break, then drag across multiple paragraphs"],
    ["Font size", "Select part of the text and apply 24 or 32"],
    ["Paragraph alignment", "Select multiple paragraphs and align center, right, or justify"],
    ["Multiple table cells", "Drag across cells or extend the range with Shift+Arrow"],
    ["Slash commands", "Type / and search, or use Arrow keys and Enter to insert a block"],
    ["Clipboard images", "Paste a screenshot and confirm the link remains under /api/media/..."],
  ],
  ko: [
    ["여러 줄과 여러 블록", "Shift+Enter 줄바꿈 후 여러 문단을 드래그해 선택"],
    ["글자 크기", "일부 글자만 선택하고 24 또는 32 적용"],
    ["문단 정렬", "여러 문단을 선택하고 가운데·오른쪽·양쪽 정렬"],
    ["표 여러 셀", "셀을 가로질러 드래그하거나 Shift+방향키로 범위 확장"],
    ["슬래시 명령", "/를 입력하고 검색하거나 방향키와 Enter로 블록 삽입"],
    ["클립보드 이미지", "화면 캡처를 붙여넣고 링크가 /api/media/...로 남는지 확인"],
  ],
  ja: [
    ["複数行と複数ブロック", "Shift+Enterで改行し、複数の段落をドラッグして選択"],
    ["文字サイズ", "一部の文字を選択し、24または32を適用"],
    ["段落の配置", "複数の段落を選択し、中央・右・両端揃えを適用"],
    ["表の複数セル", "セルをまたいでドラッグするか、Shift+矢印キーで範囲を拡張"],
    ["スラッシュコマンド", "/を入力して検索するか、矢印キーとEnterでブロックを挿入"],
    ["クリップボード画像", "スクリーンショットを貼り付け、リンクが/api/media/...として残ることを確認"],
  ],
};
