import { defineUiCopy } from "@/lib/i18n/copy";

export const WORKSPACE_SHELL_COPY = defineUiCopy({
  en: {
    offlineCommit: "Save is available after the shared draft synchronizes with the server. Offline changes are never committed automatically later.",
    owner: "Owner",
    admin: "Administrator",
    editor: "Editor",
    viewer: "Viewer",
    tokenFailed: "Could not obtain a shared-draft connection token.",
    draftReplaced: "The shared draft was replaced. Refresh the document.",
    titleRequired: "Enter a document name before saving.",
    bodyInvalid: "The document still contains unfinished input or an element that cannot be saved.",
    bodyTooManyBlocks: "This document has {count} blocks. One document can contain up to {limit} blocks.",
    bodyTooLong: "This document has {count} characters. One document can contain up to {limit} characters.",
    commitConflict: "Another save was committed first. Your current draft is preserved. Review the new base revision, then save again.",
    commitFailed: "Could not save the shared draft as a revision.",
    discardConfirm: "Discard every unsaved shared-draft change and return to the latest revision? Draft changes from other participants will also be removed.",
    discardFailed: "Could not discard the shared draft.",
    navigateConfirm: "Move to another document without saving the current edit?",
    createConfirm: "Create a new document without saving the current edit?",
    untitled: "Untitled document",
    documentConflict: "The document changed elsewhere first. Close this window, review the latest content, then edit again.",
    documentSaveFailed: "Could not save the document.",
    revisionLoadFailed: "Could not load this revision.",
    revisionRestoreConfirm: "Load revision {revision} into the shared draft? The current canonical revision and existing revisions will not change. A new revision is created only after pressing Ctrl/⌘ S or Save.",
    revisionConflict: "The document changed first. Review the latest content and try again.",
    revisionRestoreFailed: "Could not restore this revision.",
    renameSummary: "Renamed the document to “{title}”.",
    renameFailed: "Could not rename the document.",
    deleteFailed: "Could not delete the document.",
    documentRestoreFailed: "Could not restore the document.",
    purgeDocumentConfirm: "Permanently delete the “{title}” document group? An automatic backup is created first, and the action cannot be undone in the UI.",
    documentPurgeFailed: "Could not permanently delete the document.",
    emptyTrashConfirm: "Permanently delete all {count} document groups in the {workspace} trash? An automatic backup is created first.",
    emptyTrashFailed: "Could not empty the trash.",
    workspacePurgeFailed: "Could not permanently delete the workspace.",
    workspaceRestoreFailed: "Could not restore the workspace.",
    publicAccessLoadFailed: "Could not load general access status.",
    accessLoadFailed: "Could not load the users who can access this document.",
    networkError: "Check the network connection and try again.",
    shareSaveFailed: "Could not update sharing settings.",
    shareCopyFailed: "Could not copy the sharing link. Check browser permissions.",
    accessSaveFailed: "Could not save document access.",
    selectShareUser: "Select a user to share with.",
    accessDeleteFailed: "Could not remove document access.",
    candidatesLoadFailed: "Could not load users available for sharing.",
    fixBody: "Resolve the document body error first.",
    fixTitleAndBody: "Enter a document name and resolve the body error before saving.",
    draftSaved: "Draft saved",
    matchesRevision: "Same as revision",
    connecting: "Connecting",
    offline: "Offline",
    connectionError: "Connection error",
    workspaceSelect: "Select workspace",
    newWorkspace: "＋ New workspace",
    documentName: "Document name",
    documentMenu: "Document menu",
    horizontalHint: "Drag horizontally when the menu is wider than the window.",
    history: "Version history",
    revision: "Revision {revision}",
    documentLocation: "Document location",
    topLevel: "Top level",
    pdfTitle: "Save or print the latest saved revision as PDF",
    shareTitle: "Share this document with users or by link",
    share: "Share",
    createChild: "Create child document",
    childDocument: "Child document",
    discarding: "Discarding",
    discardDraft: "Discard draft",
    offlineSaveTitle: "Saving is unavailable offline.",
    saveShortcut: "Save shared draft (Ctrl/⌘ S)",
    saving: "Saving…",
    save: "Save",
    reportBug: "Report bug",
    reportBugDescription: "Record a problem with diagnostic context",
    bugDialogTitle: "Report a problem",
    bugDialogDescription: "Choose what went wrong. Nyxdoc has already frozen the recent diagnostic context.",
    bugRecorded: "Bug report recorded",
    bugRecordedDescription: "Keep this code so the operator can find the report.",
    copyBugCode: "Copy code",
    bugType: "What went wrong?",
    bugCategoryEditor: "Typing, caret, or table editing",
    bugCategorySave: "Saving or synchronization",
    bugCategoryNavigation: "Document list or navigation",
    bugCategoryPermissions: "Permissions or sharing",
    bugCategoryPerformance: "Slow or unresponsive behavior",
    bugCategoryOther: "Something else",
    bugSuggestedType: "Nyxdoc suggests a category from recent app events. You can change it.",
    bugDescriptionLabel: "What did you notice?",
    bugDescriptionPlaceholder: "Briefly describe what you expected and what happened.",
    bugSensitiveWarning: "Do not enter passwords, tokens, document content, or other secrets.",
    bugPrivacyTitle: "Diagnostic data",
    bugPrivacyDescription: "Automatically collected data contains only version, permission, sync, performance, and structural editor states. It does not contain document text, titles, links, key values, clipboard data, screenshots, tokens, or request bodies. Reports expire after 30 days.",
    bugRateLimited: "Too many reports were submitted recently. Please try again later.",
    bugFailed: "Could not record the bug report. Your document was not changed.",
    bugSubmitting: "Recording…",
    bugSubmit: "Record bug",
    accountSettings: "Account settings",
    documents: "Documents",
    createTopLevel: "Create top-level document",
    trash: "Trash",
    resizeSidebar: "Resize document list",
    resizeSidebarTitle: "Drag to resize the document list · double-click to reset",
    body: "{title} body",
    sharedDraft: "{title} shared draft",
    childDocuments: "Child documents",
    newDocument: "New document",
    revisionSavedNewest: "Saved revisions, newest first.",
    closeHistory: "Close version history",
    current: "Current",
    viewRevision: "View revision {revision}",
    loading: "Loading…",
    view: "View",
    revisionSavedToast: "Saved as a revision.",
    shareDialogTitle: "Share “{title}”",
    shareDialogDescription: "Manage per-user document access and public link access in one place.",
    closeShare: "Close sharing",
    loadingShare: "Loading sharing status…",
    sharePeople: "Share with people",
    sharePeopleDescription: "Choose a verified Nyxdoc user from the same organization email domain.",
    findUser: "Find a user by name or email",
    userPlaceholder: "Enter a name or email",
    clearUser: "Clear selected user",
    findingUsers: "Finding users…",
    noShareCandidates: "No users are available for sharing.",
    newUserRole: "Document role for the new user",
    shareAction: "Share",
    accessUsers: "People with access",
    accessUsersDescription: "Workspace permissions are inherited and cannot be reduced on this document.",
    me: "me",
    inherited: "Inherited from workspace",
    entryRole: "{name} document role",
    remove: "Remove",
    generalAccess: "General access",
    generalAccessDescription: "Publish the latest saved revision as read-only for people who are not signed in.",
    anyoneWithLink: "Anyone with the link",
    restricted: "Restricted",
    publicEnabledDescription: "Anyone with the link can view this document without signing in.",
    restrictedDescription: "Only users added above and workspace members can access this document.",
    processing: "Working…",
    makeRestricted: "Make restricted",
    publishLink: "Publish link",
    copied: "Copied",
    copyLink: "Copy link",
    restrictLinkNote: "Restricting general access disables the link immediately. Publishing it again reuses the same link.",
    returnToDocument: "Return to document",
    editDocument: "Edit document",
    createDocument: "Create document",
    position: "Location",
    saveAsRevision: "Save as revision {revision}",
    saveFirstRevision: "Save as first revision",
    editingNavigation: "Documents while editing",
    editorBody: "Document body being edited",
    changeNote: "Change note",
    optional: "Optional",
    changeNoteHint: "Leave one line so the next person or agent can understand why this change was made.",
    changeNotePlaceholder: "Example: Clarified the release date after customer feedback",
    revisionSafety: "Changes are recorded safely as a new revision without overwriting the current content.",
    readOnly: "Read only",
    revisionPreview: "Revision {revision} preview",
    closePreview: "Close revision preview",
    currentDocumentRevision: "The current document is revision {revision}.",
    revisionBody: "Revision {revision} body",
    close: "Close",
    restoring: "Loading…",
    restoreToDraft: "Load this version into the shared draft",
    renameDocument: "Rename document",
    deleteDocument: "Delete document",
    renameDescription: "Change the name shown in the document list.",
    deleteDescription: "Hide this document and its child documents from the list.",
    dialogClose: "Close",
    descendantsDeleted: "{count} child documents will also be deleted.",
    onlyDocumentDeleted: "Only this document will be deleted.",
    cannotDeleteLast: "The last document cannot be deleted. Create another document first.",
    trashRetention: "The document structure and every revision remain in Trash for 30 days and can be restored at any time.",
    cancel: "Cancel",
    rename: "Rename",
    moveToTrash: "Move {count} documents to Trash",
    unifiedTrash: "Unified Trash",
    unifiedTrashDescription: "Manage deleted documents and workspaces from every workspace in one place.",
    closeTrash: "Close Unified Trash",
    trashList: "Unified Trash list",
    deletedDocuments: "Deleted documents",
    deletedDocumentsDescription: "The original tree and every revision are preserved for 30 days, grouped by workspace.",
    noDeletedDocuments: "No deleted documents.",
    documentGroups: "{count} document groups",
    backingUpDeleting: "Backing up and deleting…",
    emptyThisTrash: "Empty this trash",
    includesChildren: "{count} documents including children",
    oneDocument: "1 document",
    deletedTimeline: "Deleted {deleted} · automatic deletion {purge}",
    restore: "Restore",
    permanentlyDelete: "Permanently delete",
    deletedWorkspaces: "Deleted workspaces",
    deletedWorkspacesDescription: "Only workspaces moved to Trash from Workspace Settings are shown.",
    noDeletedWorkspaces: "No deleted workspaces.",
    restoringWorkspace: "Restoring…",
    workspacePurgeTitle: "Permanently delete the workspace?",
    workspacePurgeDescription: "A full data and media backup is created before deletion. After completion, it cannot be restored from this screen.",
    typeWorkspaceName: "Enter the workspace name to confirm.",
    backupAndDelete: "Back up and permanently delete",
  },
  ko: {
    offlineCommit: "공유 초안이 서버와 동기화된 뒤 저장할 수 있습니다. 오프라인 저장은 나중에 자동 커밋되지 않습니다.",
    owner: "소유자",
    admin: "관리자",
    editor: "편집자",
    viewer: "뷰어",
    tokenFailed: "공유 초안 연결 토큰을 받지 못했습니다.",
    draftReplaced: "공유 초안이 교체되었습니다. 문서를 새로고침해주세요.",
    titleRequired: "저장하려면 문서 이름을 입력해주세요.",
    bodyInvalid: "본문에 아직 완료되지 않은 입력이나 저장할 수 없는 요소가 있습니다.",
    bodyTooManyBlocks: "이 문서는 {count}개 블록입니다. 문서 하나에는 최대 {limit}개 블록을 저장할 수 있습니다.",
    bodyTooLong: "이 문서는 {count}자입니다. 문서 하나에는 최대 {limit}자까지 저장할 수 있습니다.",
    commitConflict: "다른 저장이 먼저 확정되었습니다. 현재 초안은 유지됩니다. 새 기준을 확인한 뒤 다시 저장해주세요.",
    commitFailed: "공유 초안을 리비전으로 저장하지 못했습니다.",
    discardConfirm: "저장하지 않은 공유 초안 변경을 모두 버리고 마지막 리비전으로 되돌릴까요? 다른 참여자의 초안 변경도 함께 사라집니다.",
    discardFailed: "공유 초안을 버리지 못했습니다.",
    navigateConfirm: "현재 편집 중인 내용을 저장하지 않고 다른 문서로 이동할까요?",
    createConfirm: "현재 편집 중인 내용을 저장하지 않고 새 문서를 만들까요?",
    untitled: "제목 없는 문서",
    documentConflict: "다른 곳에서 문서가 먼저 바뀌었습니다. 창을 닫고 최신 내용을 확인한 뒤 다시 편집해주세요.",
    documentSaveFailed: "문서를 저장하지 못했습니다.",
    revisionLoadFailed: "이 리비전을 불러오지 못했습니다.",
    revisionRestoreConfirm: "리비전 {revision}의 내용을 공유 초안으로 불러올까요? 현재 정본과 기존 리비전은 바뀌지 않으며, Ctrl+S 또는 ‘저장’을 눌러야 새 리비전이 생깁니다.",
    revisionConflict: "문서가 먼저 변경되었습니다. 최신 내용을 확인한 뒤 다시 시도해주세요.",
    revisionRestoreFailed: "이 리비전을 복원하지 못했습니다.",
    renameSummary: "문서 이름을 “{title}”로 변경했습니다.",
    renameFailed: "문서 이름을 변경하지 못했습니다.",
    deleteFailed: "문서를 삭제하지 못했습니다.",
    documentRestoreFailed: "문서를 복구하지 못했습니다.",
    purgeDocumentConfirm: "“{title}” 문서 묶음을 영구 삭제할까요? 삭제 직전 자동 백업을 만든 뒤 진행하며, 화면에서는 되돌릴 수 없습니다.",
    documentPurgeFailed: "문서를 영구 삭제하지 못했습니다.",
    emptyTrashConfirm: "“{workspace}” 휴지통의 {count}개 문서 묶음을 모두 영구 삭제할까요? 삭제 직전 자동 백업이 만들어집니다.",
    emptyTrashFailed: "휴지통을 비우지 못했습니다.",
    workspacePurgeFailed: "워크스페이스를 영구 삭제하지 못했습니다.",
    workspaceRestoreFailed: "워크스페이스를 복구하지 못했습니다.",
    publicAccessLoadFailed: "일반 액세스 상태를 확인하지 못했습니다.",
    accessLoadFailed: "이 문서에 접근할 수 있는 사용자를 확인하지 못했습니다.",
    networkError: "네트워크 연결을 확인한 뒤 다시 시도해주세요.",
    shareSaveFailed: "공유 설정을 변경하지 못했습니다.",
    shareCopyFailed: "공유 링크를 복사하지 못했습니다. 브라우저 권한을 확인해주세요.",
    accessSaveFailed: "문서 접근 권한을 저장하지 못했습니다.",
    selectShareUser: "공유할 사용자를 선택해주세요.",
    accessDeleteFailed: "문서 접근 권한을 삭제하지 못했습니다.",
    candidatesLoadFailed: "공유할 사용자 목록을 확인하지 못했습니다.",
    fixBody: "본문 오류를 먼저 해결해주세요.",
    fixTitleAndBody: "저장하려면 문서 이름을 입력하고 본문 오류를 먼저 해결해주세요.",
    draftSaved: "초안 저장됨",
    matchesRevision: "리비전과 동일",
    connecting: "연결 중",
    offline: "오프라인",
    connectionError: "연결 오류",
    workspaceSelect: "워크스페이스 선택",
    newWorkspace: "＋ 새 워크스페이스",
    documentName: "문서 이름",
    documentMenu: "문서 메뉴",
    horizontalHint: "메뉴가 길면 좌우로 드래그하여 이동할 수 있습니다.",
    history: "변경 기록",
    revision: "리비전 {revision}",
    documentLocation: "문서 위치",
    topLevel: "최상위",
    pdfTitle: "저장된 최신 리비전을 PDF로 저장하거나 인쇄",
    shareTitle: "이 문서를 사용자 또는 링크로 공유",
    share: "공유",
    createChild: "하위 문서 만들기",
    childDocument: "하위 문서",
    discarding: "되돌리는 중",
    discardDraft: "초안 버리기",
    offlineSaveTitle: "오프라인에서는 저장할 수 없습니다.",
    saveShortcut: "공유 초안 저장 (Ctrl/⌘ S)",
    saving: "저장 중…",
    save: "저장",
    reportBug: "버그 기록",
    reportBugDescription: "문제와 진단 정보를 함께 기록",
    bugDialogTitle: "문제 기록",
    bugDialogDescription: "어떤 문제가 있었는지 골라주세요. 직전 진단 상태는 이미 고정해 두었습니다.",
    bugRecorded: "버그가 기록되었습니다",
    bugRecordedDescription: "운영자가 기록을 찾을 수 있도록 이 코드를 알려주세요.",
    copyBugCode: "코드 복사",
    bugType: "어떤 문제가 있었나요?",
    bugCategoryEditor: "입력·캐럿·표 편집",
    bugCategorySave: "저장·동기화",
    bugCategoryNavigation: "문서 목록·이동",
    bugCategoryPermissions: "권한·공유",
    bugCategoryPerformance: "느림·멈춤",
    bugCategoryOther: "그 밖의 문제",
    bugSuggestedType: "최근 앱 동작을 바탕으로 유형을 추천했습니다. 직접 바꿀 수 있습니다.",
    bugDescriptionLabel: "어떤 현상이었나요?",
    bugDescriptionPlaceholder: "기대한 동작과 실제로 일어난 일을 짧게 적어주세요.",
    bugSensitiveWarning: "비밀번호, 토큰, 문서 본문 등 비밀정보는 적지 마세요.",
    bugPrivacyTitle: "수집되는 진단 정보",
    bugPrivacyDescription: "자동 수집 정보에는 버전·권한·동기화·성능·편집기 구조 상태만 들어갑니다. 문서 본문·제목·링크·입력한 글자·클립보드·스크린샷·토큰·요청 본문은 들어가지 않으며 30일 후 삭제됩니다.",
    bugRateLimited: "최근 기록이 너무 많습니다. 잠시 후 다시 시도해주세요.",
    bugFailed: "버그를 기록하지 못했습니다. 문서 내용에는 영향이 없습니다.",
    bugSubmitting: "기록 중…",
    bugSubmit: "버그 기록",
    accountSettings: "계정 설정",
    documents: "문서",
    createTopLevel: "최상위 문서 만들기",
    trash: "휴지통",
    resizeSidebar: "문서 목록 너비 조절",
    resizeSidebarTitle: "드래그하여 문서 목록 너비 조절 · 더블클릭하여 초기화",
    body: "{title} 본문",
    sharedDraft: "{title} 공유 초안",
    childDocuments: "하위 문서",
    newDocument: "새 문서",
    revisionSavedNewest: "저장된 리비전을 최신순으로 보여줍니다.",
    closeHistory: "변경 기록 닫기",
    current: "현재",
    viewRevision: "리비전 {revision} 보기",
    loading: "불러오는 중…",
    view: "보기",
    revisionSavedToast: "리비전으로 저장되었습니다.",
    shareDialogTitle: "“{title}” 공유",
    shareDialogDescription: "사람별 문서 권한과 로그인 없는 일반 액세스를 한곳에서 관리합니다.",
    closeShare: "공유 닫기",
    loadingShare: "공유 상태를 확인하고 있습니다…",
    sharePeople: "사용자와 공유",
    sharePeopleDescription: "같은 조직 이메일 도메인으로 인증된 Nyxdoc 사용자를 선택하세요.",
    findUser: "이름 또는 이메일로 사용자 찾기",
    userPlaceholder: "이름 또는 이메일 입력",
    clearUser: "선택한 사용자 지우기",
    findingUsers: "사용자를 찾고 있습니다…",
    noShareCandidates: "공유할 수 있는 사용자를 찾지 못했습니다.",
    newUserRole: "새 사용자의 문서 권한",
    shareAction: "공유",
    accessUsers: "액세스 권한이 있는 사용자",
    accessUsersDescription: "워크스페이스 권한은 상속되며 이 문서에서 낮출 수 없습니다.",
    me: "나",
    inherited: "워크스페이스에서 상속됨",
    entryRole: "{name} 문서 권한",
    remove: "삭제",
    generalAccess: "일반 액세스",
    generalAccessDescription: "로그인하지 않은 사람에게 저장된 최신 리비전을 읽기 전용으로 공개합니다.",
    anyoneWithLink: "링크가 있는 모든 사용자",
    restricted: "제한됨",
    publicEnabledDescription: "링크를 아는 사람은 로그인 없이 이 문서를 볼 수 있습니다.",
    restrictedDescription: "위에 추가된 사용자와 워크스페이스 구성원만 접근할 수 있습니다.",
    processing: "처리 중…",
    makeRestricted: "제한됨으로 변경",
    publishLink: "링크 공개",
    copied: "복사됨",
    copyLink: "링크 복사",
    restrictLinkNote: "일반 액세스를 제한하면 링크는 즉시 열리지 않습니다. 다시 공개하면 같은 링크를 사용합니다.",
    returnToDocument: "문서로 돌아가기",
    editDocument: "문서 편집",
    createDocument: "새 문서 만들기",
    position: "위치",
    saveAsRevision: "리비전 {revision}로 저장",
    saveFirstRevision: "첫 리비전으로 저장",
    editingNavigation: "편집 중 문서 탐색",
    editorBody: "편집 중인 문서 본문",
    changeNote: "변경 메모",
    optional: "선택",
    changeNoteHint: "다음 사람이나 에이전트가 이번 변경의 이유를 이해할 수 있도록 한 줄만 남겨주세요.",
    changeNotePlaceholder: "예: 고객 피드백을 반영해 공개 일정을 구체화함",
    revisionSafety: "변경은 현재 내용을 덮어쓰지 않고 새 리비전으로 안전하게 기록됩니다.",
    readOnly: "읽기 전용",
    revisionPreview: "리비전 {revision} 미리보기",
    closePreview: "리비전 미리보기 닫기",
    currentDocumentRevision: "현재 문서는 리비전 {revision}입니다.",
    revisionBody: "리비전 {revision} 본문",
    close: "닫기",
    restoring: "불러오는 중…",
    restoreToDraft: "이 버전을 공유 초안으로 불러오기",
    renameDocument: "문서 이름 변경",
    deleteDocument: "문서 삭제",
    renameDescription: "목록에 표시할 문서 이름을 바꿉니다.",
    deleteDescription: "문서와 하위 문서를 목록에서 숨깁니다.",
    dialogClose: "닫기",
    descendantsDeleted: "하위 문서 {count}개도 함께 삭제됩니다.",
    onlyDocumentDeleted: "이 문서만 삭제됩니다.",
    cannotDeleteLast: "마지막 문서는 삭제할 수 없습니다. 먼저 새 문서를 만들어주세요.",
    trashRetention: "문서 구조와 모든 리비전은 휴지통에서 30일 동안 보관되며 언제든 복구할 수 있습니다.",
    cancel: "취소",
    rename: "이름 변경",
    moveToTrash: "{count}개 문서 휴지통으로 이동",
    unifiedTrash: "통합 휴지통",
    unifiedTrashDescription: "모든 워크스페이스의 삭제된 문서와 작업 공간을 한곳에서 관리합니다.",
    closeTrash: "통합 휴지통 닫기",
    trashList: "통합 휴지통 목록",
    deletedDocuments: "삭제된 문서",
    deletedDocumentsDescription: "워크스페이스별로 원래 트리와 모든 리비전을 30일 동안 보존합니다.",
    noDeletedDocuments: "삭제된 문서가 없습니다.",
    documentGroups: "{count}개 문서 묶음",
    backingUpDeleting: "백업 후 삭제 중…",
    emptyThisTrash: "이 휴지통 비우기",
    includesChildren: "하위 문서 포함 {count}개",
    oneDocument: "문서 1개",
    deletedTimeline: "{deleted} 삭제 · {purge} 자동 삭제",
    restore: "복구",
    permanentlyDelete: "영구 삭제",
    deletedWorkspaces: "삭제된 워크스페이스",
    deletedWorkspacesDescription: "워크스페이스 설정에서 휴지통으로 옮긴 작업 공간만 표시됩니다.",
    noDeletedWorkspaces: "삭제된 워크스페이스가 없습니다.",
    restoringWorkspace: "복구 중…",
    workspacePurgeTitle: "워크스페이스를 영구 삭제할까요?",
    workspacePurgeDescription: "전체 데이터와 미디어 백업을 먼저 만든 뒤 삭제합니다. 완료 후에는 이 화면에서 복구할 수 없습니다.",
    typeWorkspaceName: "확인을 위해 워크스페이스 이름을 입력하세요.",
    backupAndDelete: "백업 후 영구 삭제",
  },
  ja: {
    offlineCommit: "共有下書きがサーバーと同期された後に保存できます。オフラインの変更が後で自動確定されることはありません。",
    owner: "所有者",
    admin: "管理者",
    editor: "編集者",
    viewer: "閲覧者",
    tokenFailed: "共有下書きの接続トークンを取得できませんでした。",
    draftReplaced: "共有下書きが置き換えられました。文書を再読み込みしてください。",
    titleRequired: "保存する前に文書名を入力してください。",
    bodyInvalid: "文書本文に未完了の入力、または保存できない要素があります。",
    bodyTooManyBlocks: "この文書には{count}個のブロックがあります。1文書に保存できる上限は{limit}ブロックです。",
    bodyTooLong: "この文書は{count}文字です。1文書に保存できる上限は{limit}文字です。",
    commitConflict: "別の保存が先に確定しました。現在の下書きは保持されています。新しい基準リビジョンを確認して、もう一度保存してください。",
    commitFailed: "共有下書きをリビジョンとして保存できませんでした。",
    discardConfirm: "未保存の共有下書き変更をすべて破棄して最新リビジョンへ戻しますか？他の参加者の下書き変更も削除されます。",
    discardFailed: "共有下書きを破棄できませんでした。",
    navigateConfirm: "現在の編集を保存せず別の文書へ移動しますか？",
    createConfirm: "現在の編集を保存せず新しい文書を作成しますか？",
    untitled: "無題の文書",
    documentConflict: "別の場所で文書が先に変更されました。この画面を閉じ、最新内容を確認してから再度編集してください。",
    documentSaveFailed: "文書を保存できませんでした。",
    revisionLoadFailed: "このリビジョンを読み込めませんでした。",
    revisionRestoreConfirm: "リビジョン{revision}を共有下書きへ読み込みますか？現在の正本と既存リビジョンは変わりません。Ctrl/⌘ Sまたは「保存」を押したときだけ新しいリビジョンが作成されます。",
    revisionConflict: "文書が先に変更されました。最新内容を確認して再試行してください。",
    revisionRestoreFailed: "このリビジョンを復元できませんでした。",
    renameSummary: "文書名を「{title}」へ変更しました。",
    renameFailed: "文書名を変更できませんでした。",
    deleteFailed: "文書を削除できませんでした。",
    documentRestoreFailed: "文書を復元できませんでした。",
    purgeDocumentConfirm: "「{title}」文書グループを完全削除しますか？直前に自動バックアップを作成し、画面から元に戻すことはできません。",
    documentPurgeFailed: "文書を完全削除できませんでした。",
    emptyTrashConfirm: "「{workspace}」のゴミ箱にある{count}件の文書グループをすべて完全削除しますか？直前に自動バックアップが作成されます。",
    emptyTrashFailed: "ゴミ箱を空にできませんでした。",
    workspacePurgeFailed: "ワークスペースを完全削除できませんでした。",
    workspaceRestoreFailed: "ワークスペースを復元できませんでした。",
    publicAccessLoadFailed: "一般アクセス状態を読み込めませんでした。",
    accessLoadFailed: "この文書へアクセスできるユーザーを読み込めませんでした。",
    networkError: "ネットワーク接続を確認して再試行してください。",
    shareSaveFailed: "共有設定を変更できませんでした。",
    shareCopyFailed: "共有リンクをコピーできませんでした。ブラウザー権限を確認してください。",
    accessSaveFailed: "文書アクセス権を保存できませんでした。",
    selectShareUser: "共有するユーザーを選択してください。",
    accessDeleteFailed: "文書アクセス権を削除できませんでした。",
    candidatesLoadFailed: "共有可能なユーザー一覧を読み込めませんでした。",
    fixBody: "先に文書本文のエラーを解決してください。",
    fixTitleAndBody: "文書名を入力し、本文のエラーを解決してから保存してください。",
    draftSaved: "下書き保存済み",
    matchesRevision: "リビジョンと同じ",
    connecting: "接続中",
    offline: "オフライン",
    connectionError: "接続エラー",
    workspaceSelect: "ワークスペースを選択",
    newWorkspace: "＋ 新しいワークスペース",
    documentName: "文書名",
    documentMenu: "文書メニュー",
    horizontalHint: "メニューが画面より広い場合は左右へドラッグできます。",
    history: "変更履歴",
    revision: "リビジョン {revision}",
    documentLocation: "文書の場所",
    topLevel: "最上位",
    pdfTitle: "最新の保存済みリビジョンをPDF保存または印刷",
    shareTitle: "この文書をユーザーまたはリンクで共有",
    share: "共有",
    createChild: "子文書を作成",
    childDocument: "子文書",
    discarding: "破棄中",
    discardDraft: "下書きを破棄",
    offlineSaveTitle: "オフラインでは保存できません。",
    saveShortcut: "共有下書きを保存（Ctrl/⌘ S）",
    saving: "保存中…",
    save: "保存",
    reportBug: "不具合を記録",
    reportBugDescription: "問題と診断情報を記録",
    bugDialogTitle: "問題を報告",
    bugDialogDescription: "問題の種類を選んでください。直前の診断状態はすでに固定されています。",
    bugRecorded: "不具合を記録しました",
    bugRecordedDescription: "管理者が記録を確認できるよう、このコードをお知らせください。",
    copyBugCode: "コードをコピー",
    bugType: "どのような問題ですか？",
    bugCategoryEditor: "入力・キャレット・表の編集",
    bugCategorySave: "保存・同期",
    bugCategoryNavigation: "文書一覧・移動",
    bugCategoryPermissions: "権限・共有",
    bugCategoryPerformance: "遅い・応答しない",
    bugCategoryOther: "その他",
    bugSuggestedType: "最近のアプリ操作から種類を提案しました。変更できます。",
    bugDescriptionLabel: "どのような現象でしたか？",
    bugDescriptionPlaceholder: "期待した動作と実際の結果を短く入力してください。",
    bugSensitiveWarning: "パスワード、トークン、文書本文などの秘密情報は入力しないでください。",
    bugPrivacyTitle: "診断データ",
    bugPrivacyDescription: "自動収集データには、バージョン、権限、同期、性能、編集構造の状態だけが含まれます。文書本文、タイトル、リンク、入力文字、クリップボード、画面、トークン、リクエスト本文は含まず、30日後に削除します。",
    bugRateLimited: "最近の報告が多すぎます。しばらくしてから再試行してください。",
    bugFailed: "不具合を記録できませんでした。文書内容には影響ありません。",
    bugSubmitting: "記録中…",
    bugSubmit: "不具合を記録",
    accountSettings: "アカウント設定",
    documents: "文書",
    createTopLevel: "最上位文書を作成",
    trash: "ゴミ箱",
    resizeSidebar: "文書一覧の幅を変更",
    resizeSidebarTitle: "ドラッグで文書一覧の幅を変更 · ダブルクリックでリセット",
    body: "{title}の本文",
    sharedDraft: "{title}の共有下書き",
    childDocuments: "子文書",
    newDocument: "新しい文書",
    revisionSavedNewest: "保存済みリビジョンを新しい順に表示します。",
    closeHistory: "変更履歴を閉じる",
    current: "現在",
    viewRevision: "リビジョン{revision}を表示",
    loading: "読み込み中…",
    view: "表示",
    revisionSavedToast: "リビジョンとして保存しました。",
    shareDialogTitle: "「{title}」を共有",
    shareDialogDescription: "ユーザー別の文書権限と、ログイン不要の一般アクセスをまとめて管理します。",
    closeShare: "共有を閉じる",
    loadingShare: "共有状態を確認中…",
    sharePeople: "ユーザーと共有",
    sharePeopleDescription: "同じ組織メールドメインで認証済みのNyxdocユーザーを選択してください。",
    findUser: "名前またはメールでユーザーを検索",
    userPlaceholder: "名前またはメールを入力",
    clearUser: "選択したユーザーを解除",
    findingUsers: "ユーザーを検索中…",
    noShareCandidates: "共有できるユーザーが見つかりません。",
    newUserRole: "新しいユーザーの文書権限",
    shareAction: "共有",
    accessUsers: "アクセス権のあるユーザー",
    accessUsersDescription: "ワークスペース権限は継承され、この文書では下げられません。",
    me: "自分",
    inherited: "ワークスペースから継承",
    entryRole: "{name}の文書権限",
    remove: "削除",
    generalAccess: "一般アクセス",
    generalAccessDescription: "ログインしていない人へ、最新の保存済みリビジョンを読み取り専用で公開します。",
    anyoneWithLink: "リンクを知っている全員",
    restricted: "制限付き",
    publicEnabledDescription: "リンクを知っている人はログインせずこの文書を閲覧できます。",
    restrictedDescription: "上で追加されたユーザーとワークスペースメンバーだけがアクセスできます。",
    processing: "処理中…",
    makeRestricted: "制限付きへ変更",
    publishLink: "リンクを公開",
    copied: "コピーしました",
    copyLink: "リンクをコピー",
    restrictLinkNote: "一般アクセスを制限するとリンクは直ちに無効になります。再公開すると同じリンクを使用します。",
    returnToDocument: "文書へ戻る",
    editDocument: "文書を編集",
    createDocument: "新しい文書を作成",
    position: "場所",
    saveAsRevision: "リビジョン{revision}として保存",
    saveFirstRevision: "最初のリビジョンとして保存",
    editingNavigation: "編集中の文書ナビゲーション",
    editorBody: "編集中の文書本文",
    changeNote: "変更メモ",
    optional: "任意",
    changeNoteHint: "次の人やエージェントが変更理由を理解できるよう、1行だけ残してください。",
    changeNotePlaceholder: "例：顧客フィードバックを反映して公開日を明確化",
    revisionSafety: "現在の内容を上書きせず、新しいリビジョンとして安全に記録します。",
    readOnly: "読み取り専用",
    revisionPreview: "リビジョン{revision}のプレビュー",
    closePreview: "リビジョンプレビューを閉じる",
    currentDocumentRevision: "現在の文書はリビジョン{revision}です。",
    revisionBody: "リビジョン{revision}の本文",
    close: "閉じる",
    restoring: "読み込み中…",
    restoreToDraft: "この版を共有下書きへ読み込む",
    renameDocument: "文書名を変更",
    deleteDocument: "文書を削除",
    renameDescription: "文書一覧に表示される名前を変更します。",
    deleteDescription: "文書と子文書を一覧から非表示にします。",
    dialogClose: "閉じる",
    descendantsDeleted: "子文書{count}件も一緒に削除されます。",
    onlyDocumentDeleted: "この文書だけが削除されます。",
    cannotDeleteLast: "最後の文書は削除できません。先に新しい文書を作成してください。",
    trashRetention: "文書構造とすべてのリビジョンはゴミ箱で30日間保持され、いつでも復元できます。",
    cancel: "キャンセル",
    rename: "名前を変更",
    moveToTrash: "{count}件の文書をゴミ箱へ移動",
    unifiedTrash: "統合ゴミ箱",
    unifiedTrashDescription: "すべてのワークスペースの削除済み文書とワークスペースをまとめて管理します。",
    closeTrash: "統合ゴミ箱を閉じる",
    trashList: "統合ゴミ箱一覧",
    deletedDocuments: "削除済み文書",
    deletedDocumentsDescription: "ワークスペースごとに元のツリーとすべてのリビジョンを30日間保持します。",
    noDeletedDocuments: "削除済み文書はありません。",
    documentGroups: "文書グループ{count}件",
    backingUpDeleting: "バックアップ後に削除中…",
    emptyThisTrash: "このゴミ箱を空にする",
    includesChildren: "子文書を含む{count}件",
    oneDocument: "文書1件",
    deletedTimeline: "{deleted}に削除 · {purge}に自動削除",
    restore: "復元",
    permanentlyDelete: "完全削除",
    deletedWorkspaces: "削除済みワークスペース",
    deletedWorkspacesDescription: "ワークスペース設定からゴミ箱へ移動したワークスペースだけを表示します。",
    noDeletedWorkspaces: "削除済みワークスペースはありません。",
    restoringWorkspace: "復元中…",
    workspacePurgeTitle: "ワークスペースを完全削除しますか？",
    workspacePurgeDescription: "削除前にデータとメディアの完全バックアップを作成します。完了後、この画面からは復元できません。",
    typeWorkspaceName: "確認のためワークスペース名を入力してください。",
    backupAndDelete: "バックアップ後に完全削除",
  },
});
